[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
lib_deps =
    M5Unified
    https://github.com/m5stack/M5Hat-Mini-JoyC/archive/refs/tags/0.0.1.zip
    WiFi
    lemmingdev/ESP32-BLE-Gamepad @ ^0.7.4

; ***** !IMPORTANT *************************************************************
; Note manual fix for <.pio/libdeps/esp32dev/ESP32-BLE-Gamepad/BleNUS.cpp>
;   MUST #include <Arduino.h> at top of file
; (fix after you get compilation errors of BleNUS.cpp within platformio project)
; ***** !IMPORTANT *************************************************************

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 1500000

board_upload.flash_size = 4MB

; # Ensure PlatformIO knows we have a larger flash and custom partitions
; board_build.partitions = partitions.csv
; board_build.flash_size = 4MB
; board_upload.maximum_size = 1536000

build_flags = -D CORE_DEBUG_LEVEL=0
